image: kitaitimakoto/rsass-ruby

variables:
  RSASS: /usr/bin/rsass

pages:
  script:
    - rake all
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
