image: kitaitimakoto/rsass-ruby

variables:
  RSASS: /usr/bin/rsass

pages:
  script:
    - rake index.html
    - mkdir public
    - mv dist public/
    - mv pkg public/
    - mv index.html public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
